// <auto-generated />
namespace TravelApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewTravels2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTravels2));
        
        string IMigrationMetadata.Id
        {
            get { return "202301160039346_NewTravels2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
